package world.deslauriers.tree.domain;

public enum RelationshipName {
	
	MARRIED,
	DIVORCED,
	PARTNERS,
	FATHER_SON,
	MOTHER_SON,
	FATHER_DAUGHTHER,
	MOTHER_DAUGHTER,
	BROTHERS,
	BROTHER_SISTER,
	SISTERS,
	UNCLE_NEPHEW,
	UNCLE_NIECE,
	AUNT_NEPHEW,
	AUNT_NIECE,
	GRANDFATHER_GRANDSON,
	GRANDMOTHER_GRANDSON,
	GRANDFATHER_GRANDDAUTHER,
	GRANDMOTHER_GRANDDAUGHTER,
	COUSINS,
	STEPFATHER_STEPSON,
	STEPMOTHER_STEPSON,
	STEPFATHER_STEPDAUGHTER,
	STEPMOTHER_STEPDAUGHTER,
}
